create table if not exists public.signals (
  id integer generated by default as identity primary key,
  created_at timestamp without time zone default now(),
  pair varchar(20) not null,
  mode varchar(20) default 'swing' not null,
  signal varchar(10) default 'WAIT' not null,
  status varchar(30) default 'NEW' not null,
  entry_min double precision,
  entry_max double precision,
  stop_loss double precision,
  take_profit_1 double precision,
  take_profit_2 double precision,
  take_profit_3 double precision,
  risk_reward double precision,
  confidence integer default 0 not null,
  lot_size double precision,
  risk_amount_usd double precision,
  account_type varchar(10) default 'USD' not null,
  balance double precision default 0 not null,
  risk_percent double precision default 1 not null,
  h4_bias varchar(20) default 'NEUTRAL' not null,
  h1_confirmation varchar(30) default 'NONE' not null,
  reason text default '' not null,
  raw_json text default '{}' not null
);

create index if not exists ix_signals_created_at on public.signals (created_at);
create index if not exists ix_signals_pair on public.signals (pair);
